# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Side_Viewer
                                 A QGIS plugin
 Enables visualizing the points in 3D space and toggling different flights
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-24
        copyright            : (C) 2018 by Skylark Drones
        email                : manav@stanford.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Side_Viewer class from file Side_Viewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .side_viewer import Side_Viewer
    return Side_Viewer(iface)
