# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaveChunk
                                 A QGIS plugin
 Saves a chunk to the desired location
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-26
        copyright            : (C) 2018 by Skylark Drones
        email                : manav@stanford.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SaveChunk class from file SaveChunk.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .save_chunk import SaveChunk
    return SaveChunk(iface)
